name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!renovate/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - run: yarn
      - run: yarn format --check
      - run: yarn lint
      - run: yarn build
